---
version: "3.6"
services:

  db:
    image: "postgres:18.4-alpine"
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet_hotel
    ports:
      - "5437:5432"
  redis:
    image: "redis:8.10-alpine"
    container_name: cache
    restart: unless-stopped
    ports:
      - "6381:6379"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - "8088:80"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet_hotel_service
    #restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8087:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pet_hotel
    depends_on:
      - db
      - redis
