FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    SECRET_KEY=dummy \
    DEBUG=False \
    ENVIRONMENT=DEV

WORKDIR /opt/pet_hotel

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

CMD ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn pet_hotel.wsgi:application --bind 0.0.0.0:8000 --workers 1 --reload"]
