# Generated by Django 5.2.17 on 2026-08-30 14:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('main_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_exterior', models.CharField(blank=True, help_text='Phone in Exterior Country', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, spaces, hyphens, parentheses, and optional +', regex='^\\+?[0-9\\s\\-()]+$')])),
                ('phone_home_country', models.CharField(blank=True, help_text='Phone in Home Country', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, spaces, hyphens, parentheses, and optional +', regex='^\\+?[0-9\\s\\-()]+$')])),
            ],
            options={
                'verbose_name': 'Citizen',
                'verbose_name_plural': 'Citizens',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('main_address', models.TextField(blank=True, null=True)),
                ('city_code', models.CharField(db_index=True, max_length=20)),
                ('region_code', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'indexes': [models.Index(fields=['city_code', 'region_code'], name='embassy_uni_city_co_9872aa_idx'), models.Index(fields=['name'], name='embassy_uni_name_c73d95_idx')],
            },
        ),
        migrations.CreateModel(
            name='CitizenUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateField(blank=True, help_text='Enrollment Date', null=True)),
                ('graduation_date', models.DateField(blank=True, help_text='Graduation Date', null=True)),
                ('stop_date', models.DateField(blank=True, help_text='Date when student stop attending to university. May be the same as graduation_date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is Active Student')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_university_relations', to='embassy.citizen')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_citizen_relations', to='embassy.university')),
            ],
            options={
                'verbose_name': 'Citizen University Relation',
                'verbose_name_plural': 'Citizen University Relations',
            },
        ),
        migrations.AddField(
            model_name='citizen',
            name='universities',
            field=models.ManyToManyField(blank=True, null=True, related_name='citizens', through='embassy.CitizenUniversity', to='embassy.university'),
        ),
        migrations.AddIndex(
            model_name='citizenuniversity',
            index=models.Index(fields=['citizen', 'university'], name='embassy_cit_citizen_1eb831_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['first_surname', 'first_name'], name='embassy_cit_first_s_be05b3_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['main_email'], name='embassy_cit_main_em_43e29f_idx'),
        ),
    ]
