# Generated by Django 5.2.17 on 2026-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embassy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city_code',
            field=models.CharField(choices=[('moscow', 'moscow'), ('saint_petersburg', 'saint_petersburg')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='region_code',
            field=models.CharField(choices=[('leningrad_oblast', 'leningrad_oblast'), ('mo', 'mo')], db_index=True, max_length=100),
        ),
    ]
