# Generated by Django 5.2.17 on 2026-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embassy', '0002_alter_university_city_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citizenuniversity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
