# Generated by Django 5.2.17 on 2026-09-03 16:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embassy', '0003_citizen_is_deleted_citizenuniversity_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('html', models.TextField(verbose_name='html')),
            ],
            options={
                'verbose_name': 'Mail Template',
                'verbose_name_plural': 'Mail Templates',
            },
        ),
        migrations.AlterField(
            model_name='citizen',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_surname',
            field=models.CharField(max_length=100, verbose_name='first surname'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='main_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='main email'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='phone_exterior',
            field=models.CharField(blank=True, help_text='Phone in exterior country', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, spaces, hyphens, parentheses, and optional +', regex='^\\+?[0-9\\s\\-()]+$')], verbose_name='phone exterior'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='phone_home_country',
            field=models.CharField(blank=True, help_text='Phone in home country', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, spaces, hyphens, parentheses, and optional +', regex='^\\+?[0-9\\s\\-()]+$')], verbose_name='phone home country'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='second_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='second surname'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='secondary email'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='universities',
            field=models.ManyToManyField(blank=True, null=True, related_name='citizens', through='embassy.CitizenUniversity', to='embassy.university', verbose_name='universities'),
        ),
        migrations.AlterField(
            model_name='citizenuniversity',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_university_relations', to='embassy.citizen', verbose_name='citizen'),
        ),
        migrations.AlterField(
            model_name='citizenuniversity',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Enrollment Date', null=True, verbose_name='enrollment date'),
        ),
        migrations.AlterField(
            model_name='citizenuniversity',
            name='graduation_date',
            field=models.DateField(blank=True, help_text='Graduation Date', null=True, verbose_name='graduation date'),
        ),
        migrations.AlterField(
            model_name='citizenuniversity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Active Student', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='citizenuniversity',
            name='stop_date',
            field=models.DateField(blank=True, help_text='Date when student stopped attending university. May be the same as graduation_date', null=True, verbose_name='stop date'),
        ),
        migrations.AlterField(
            model_name='citizenuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_citizen_relations', to='embassy.university', verbose_name='university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='city_code',
            field=models.CharField(choices=[('moscow', 'moscow'), ('saint_petersburg', 'saint_petersburg')], db_index=True, max_length=100, verbose_name='city code'),
        ),
        migrations.AlterField(
            model_name='university',
            name='main_address',
            field=models.TextField(blank=True, null=True, verbose_name='main address'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='region_code',
            field=models.CharField(choices=[('leningrad_oblast', 'leningrad_oblast'), ('mo', 'mo')], db_index=True, max_length=100, verbose_name='region code'),
        ),
    ]
