# Generated by Django 5.2.17 on 2026-09-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embassy', '0004_alter_citizen_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID number'),
        ),
    ]
