# Generated by Django 5.2.17 on 2026-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embassy', '0006_citizenuploadlog_alter_citizen_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID number'),
        ),
    ]
