# Generated by Django 5.2.17 on 2026-10-01 18:14

import apps.embassy.models.registration_token
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embassy', '0007_alter_citizen_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, help_text='Optional note, e.g. intended recipient', max_length=200)),
                ('expires_at', models.DateTimeField(default=apps.embassy.models.registration_token._default_expires_at)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registration Token',
                'verbose_name_plural': 'Registration Tokens',
            },
        ),
    ]
