server {
  listen 80;

  location /pet_hotel/ {
    proxy_pass http://backend/;
    include snippets.d/proxy_params;
  }

  location /admin {
    proxy_pass http://admin;
    include snippets.d/proxy_params;
  }

  location /static/ {
      proxy_pass http://admin;
      include snippets.d/proxy_params;
  }
}
