server {
  listen 80;

  # General #
  ###########

  location /__version__ {
    proxy_pass http://backend;
    include snippets.d/proxy_params;
  }

  location /__heartbeat__ {
    proxy_pass http://backend;
    include snippets.d/proxy_params;
  }

  location /__lbheartbeat__ {
    proxy_pass http://backend;
    include snippets.d/proxy_params;
  }

  # Backend related #
  # ############### #

  location /pet_hotel/ {
    proxy_pass http://backend/;
    include snippets.d/proxy_params;
  }

  location /admin {
    proxy_pass http://backend;
    include snippets.d/proxy_params;
  }

  location /static/ {
      alias /opt/app/backend/static/;
      try_files $uri $uri/ =404;
  }
}
