map $scheme:$http2:$http_x_url_scheme:$http_x_forwarded_proto $forwarded_proto {
  default "http";
  "~h2:" "https";
  "~https" "https";
}

map $http_x_forwarded_host $x_forwarded_host {
    default  $http_x_forwarded_host;
    ''       $http_host;
}
