# Generated by Django 5.2.17 on 2026-08-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=3, null=True, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('rating', models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=3, null=True, verbose_name='Rating')),
                ('city_code', models.CharField(choices=[('moscow', 'moscow'), ('saint_petersburg', 'saint_petersburg')], db_index=True, max_length=100)),
                ('region_code', models.CharField(choices=[('leningrad_oblast', 'leningrad_oblast'), ('mo', 'mo')], db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='hotel.partner')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'indexes': [models.Index(fields=['city_code', 'region_code'], name='hotel_hotel_city_co_a51baf_idx')],
            },
        ),
    ]
