# Generated by Django 5.2.17 on 2026-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('failed', 'failed')], max_length=10, verbose_name='status'),
        ),
    ]
