# Generated by Django 5.2.17 on 2026-09-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_sentemail_status'),
        ('mail', '0002_mailtemplate_add_content_type'),
    ]

    operations = [
    ]
