# Generated by Django 5.2.17 on 2026-09-05 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mail', '0004_mailtemplate_add_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
